### ISSUE TITLE
KeyError: 'location'

### ISSUE THREAD

**Issue by itinybad** [WeiSanJin/yiban#3]
```
2021-06-30 22:51:46  登录成功：xxx
Traceback (most recent call last):
  File ".\submit.py", line 21, in <module>
    result_auth = yb.auth()
  File "C:\Users\TinyBad\Desktop\yiban-master\yiban\__init__.py", line 54, in auth
    allow_redirects=False).headers["Location"]
  File "C:\Users\TinyBad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'
```
![image](https://user-images.githubusercontent.com/13375605/123982995-1906f280-d9f6-11eb-92f8-1961124f3645.png)

**Comment by WeiSanJin** [comment]
重新抓包即可
